name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: vendor
      run: go mod vendor

    - name: download
      run: go mod download

    - name: build
      run: go build -v ./bin/app.go


    - name: Test
      run: go test -v ./...
